### ISSUE TITLE
Retina Support

### ISSUE THREAD

**Issue by chrisle** [codegl/tracegl#46]
Low priority. Retina support? :)

**Comment by codegl** [comment]
I have explicit retina support for OSX, which worked last time i tested it. However if you run it on windows on a retina machine, the normal mode actually scales up the browser window using pixel scaling. In that mode i have no way to provide proper retina support, since the browser itself runs in a scaled up broken resolution. I have yet to try it on a chromebook pixel though, but if they support the devicepixel thing, it should work.
